run:
  tests: true
  modules-download-mode: vendor
  skip-dirs:
    - vendor
    - pkg/mod
linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - unused
    - whitespace
linters-settings:
  govet:
    check-shadowing: true
issues:
  exclude-use-default: false
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    - 'shadow: declaration of "err" shadows declaration at line (\d+)'
